id: ProductDetail_LongFormContainer
type: widget
subtype: RNContainerWidget
template:
  ordered:
    - events:
        ordered: []
    - layout: column
    - justify: flex-start
    - align: flex-start
    - gap: 4
    - padding:
        ordered:
          - left: 0
          - right: 0
          - top: 0
          - bottom: 0
    - width: full
style:
  ordered: []
position2:
  position2:
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition:
    ordinal: 27
createdAt: 2022-07-27T21:10:46.522Z
screen: ProductDetail
