id: ProductDetail_ReturnPolicyText
type: widget
subtype: RNTextWidget
template:
  ordered:
    - value: '{{ getItemDetail.data.returnPolicy[0] || "None"}}'
    - size: medium
    - weight: normal
    - width: full
    - textAlign: left
style:
  ordered: []
position2:
  position2:
    container: ProductDetail_ReturnPolicyContainer
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition:
    ordinal: 1
createdAt: 2022-07-27T21:10:42.709Z
screen: ProductDetail
