id: Products_ProductCollection
type: widget
subtype: RNCollectionViewV2Widget
template:
  ordered:
    - cardStyle: flat
    - titleByIndex: '{{item.title}}'
    - subtitleByIndex: '{{ item.brand }} {{ item[''price/currency''] }}{{item[''price/value'']}}'
    - showSeparator: true
    - selectedPageIndex: 0
    - cardType: compact
    - serverPaginated: false
    - data: '{{ getItems.data }}'
    - selectedItem: '{}'
    - prefixTypeByIndex: image
    - suffixTypeByIndex: none
    - prefixIconByIndex: bold/interface-user-single
    - prefixImageSizeByIndex: 1 to 1
    - cardSize: full
    - suffixIconByIndex: bold/interface-arrows-button-right
    - scrollDirection: vertical
    - prefixImageStyleByIndex: round
    - itemMode: dynamic
    - prefixImageSourceByIndex: '{{ item.thumbnailImage }}'
    - events:
        - ordered:
            - event: press
            - type: navigator
            - method: navigateTo
            - pluginId: ''
            - targetId: null
            - params:
                ordered:
                  - screenPluginId: ProductDetail
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: press
            - type: state
            - method: setValue
            - pluginId: selectedItem
            - targetId: null
            - params:
                ordered:
                  - value: '{{ self.selectedItem }}'
            - waitType: debounce
            - waitMs: '0'
    - _ids: []
    - bodyByIndex: '{{item.sales}}'
    - suffixValueByIndex: 'false'
    - suffixTextByIndex: text
    - subtitleLengthByIndex:
        array: []
position2:
  position2:
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition:
    ordinal: 2
createdAt: 2022-07-27T16:55:33.483Z
screen: Products
