id: Products_SearchInput
type: widget
subtype: RNTextInputWidget
template:
  ordered:
    - iconAfter: ''
    - showCharacterCount: false
    - maxLength: null
    - customValidation: ''
    - patternType: ''
    - hideValidationMessage: false
    - validationMessage: ''
    - pattern: ''
    - formDataKey: '{{ self.id }}'
    - value: ''
    - labelCaption: ''
    - placeholder: Search by name
    - label: Search
    - _validate: false
    - invalid: false
    - iconBefore: bold/interface-search
    - minLength: null
    - events:
        - ordered:
            - event: change
            - type: datasource
            - method: trigger
            - pluginId: getItems
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '100'
    - autoCapitalize: none
    - disabled: false
    - required: false
style:
  ordered: []
position2:
  position2:
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition: {}
createdAt: 2022-07-27T17:18:04.770Z
screen: Products
