id: Products
type: screen
subtype: Screen
template:
  ordered:
    - title: Products
    - headerLeftActions: []
    - headerRightActions:
        - ordered:
            - type: icon
            - value: bold/interface-text-formatting-filter-2-alternate
            - event:
                ordered:
                  - event: click
                  - method: modal
                  - pluginId: ''
                  - type: navigator
                  - waitMs: 0
                  - waitType: debounce
                  - params:
                      ordered:
                        - screenPluginId: Filters
    - gap: 8
    - padding:
        object:
          left: 12
          right: 12
          top: 8
          bottom: 8
    - events:
        - ordered:
            - event: visible
            - type: datasource
            - method: trigger
            - pluginId: getItems
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
            - enabled: '{{ !getItems.data.id.length }}'
createdAt: 2022-07-27T16:55:33.483Z
