id: ProductDetail
type: screen
subtype: Screen
template:
  ordered:
    - title: ' '
    - headerLeftActions: []
    - headerRightActions: []
    - gap: 8
    - padding:
        object:
          left: 12
          right: 12
          top: 8
          bottom: 8
    - events: []
createdAt: 2022-07-27T21:04:54.196Z
