id: ProductDetail_BasicKeyText
type: widget
subtype: RNTextWidget
template:
  ordered:
    - value: |-
        Price
        Brand
        Rating
    - size: medium
    - weight: semibold
    - width: full
    - textAlign: left
style:
  ordered: []
position2:
  position2:
    container: ProductDetail_BasicDetailContainer
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition: {}
createdAt: 2022-07-27T21:06:36.950Z
screen: ProductDetail
