id: ProductDetail_Image
type: widget
subtype: RNImageWidget
template:
  ordered:
    - src: '{{ getItemDetail.data.thumbnailImage[0] }}'
    - ratio: 2
    - mode: contain
    - cornerType: round
style:
  ordered: []
position2:
  position2:
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition:
    ordinal: 23
createdAt: 2022-07-27T21:06:12.404Z
screen: ProductDetail
