id: ProductDetail_BasicValueText
type: widget
subtype: RNTextWidget
template:
  ordered:
    - value: >
        {{ getItemDetail.data['price/currency'][0] }} {{
        getItemDetail.data['price/value'][0] }}

        {{ getItemDetail.data.brand[0] }}

        {{ getItemDetail.data.stars[0]}}
    - size: medium
    - weight: normal
    - width: full
    - textAlign: right
style:
  ordered: []
position2:
  position2:
    container: ProductDetail_BasicDetailContainer
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition:
    ordinal: 1
createdAt: 2022-07-27T21:07:26.464Z
screen: ProductDetail
