id: ProductDetail_WebView
type: widget
subtype: RNWebViewWidget
template:
  ordered:
    - events:
        ordered: []
    - url: '{{ getItemDetail.data[''url''][0] }}'
    - buttonText: Open Url
    - buttonSize: large
    - iconAfter: ''
    - iconBefore: ''
    - disabled: false
    - width: full
style:
  ordered: []
position2:
  position2:
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition:
    ordinal: 25
createdAt: 2022-07-27T21:15:49.427Z
screen: ProductDetail
