id: ProductDetail_ReturnPolicyHeader
type: widget
subtype: RNTextWidget
template:
  ordered:
    - value: Return Policy
    - size: medium
    - weight: semibold
    - width: full
    - textAlign: left
style:
  ordered: []
position2:
  position2:
    container: ProductDetail_ReturnPolicyContainer
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition: {}
createdAt: 2022-07-27T21:10:40.105Z
screen: ProductDetail
