id: Products_Fab
type: widget
subtype: RNFabWidget
template:
  ordered:
    - events:
        - ordered:
            - event: click
            - type: widget
            - method: open
            - pluginId: Products_Scanner
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
    - icon: bold/interface-id-voice-scan
    - text: Find by barcode
    - disabled: false
style:
  ordered: []
position2:
  position2:
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition:
    ordinal: 28
createdAt: 2022-07-27T21:17:59.363Z
screen: Products
