id: ProductDetail_DescriptionHeader
type: widget
subtype: RNTextWidget
template:
  ordered:
    - value: Description
    - size: medium
    - weight: semibold
    - width: full
    - textAlign: left
style:
  ordered: []
position2:
  position2:
    container: ProductDetail_DescriptionContainer
    height: 5
    width: 3
mobileAppPosition:
  mobilePosition: {}
createdAt: 2022-07-27T21:12:28.261Z
screen: ProductDetail
