version: 43.0.9
pageUuid: 2cb8ca98-b9b5-11ec-86f2-8f3a779cb2e9
appTemplate:
  appThemeId: 2
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
  rootScreen: tabscreen
  isMobileApp: true
  version: 2.97.0
  multiScreenMobileApp: true
  markdownLinkBehavior: auto
